#!/bin/sh

gst-launch v4l2src always-copy=false chain-ipipe=true ! video/x-raw-yuv,format='(fourcc)'NV12,width=640,height=480, framerate='(fraction)'30/1 ! dmaiaccel ! TIDmaiVideoSink videoStd=D1_PAL videoOutput=composite accelFrameCopy=FALSE sync=false
